# --- Selección de tema ---
theme = "xscriptor_candypop"

# --- Ajustes generales del editor ---
[editor]
line-number = "relative"     # "absolute" | "relative" | "none"
cursorline = true
color-modes = true           # muestra el modo con colores (NORMAL/INSERT/SELECT)
true-color = true            # usa 24-bit si tu terminal lo soporta
mouse = true
auto-pairs = true
idle-timeout = 400           # ms para eventos de “idle” (lint/autocomplete, etc.)
bufferline = "always"
completion-trigger-len = 1

# --- Forma del cursor por modo ---
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

# --- Statusline (qué se ve y dónde) ---
[editor.statusline]
left   = ["mode", "spinner", "file-name"]
center = ["diagnostics"]
right  = ["selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# --- Guías de indentación ---
[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

# --- Visualización de espacios/tabulaciones ---
[editor.whitespace.render]
space = "all"        # "none" | "all" | "boundary"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

# --- Ajuste de línea suave (soft-wrap) ---
[editor.soft-wrap]
enable = true
wrap-at-text-width = false
max-wrap = 20
wrap-indicator = "↲"


[editor.file-picker]
hidden = false
git-ignore = true


# --- LSP (comportamiento general) ---
[editor.lsp]
display-messages = true
auto-signature-help = true
snippets = true


